theme: jekyll-theme-cayman
title: Jacob Gilliam - Computer Science ePortfolio
description: Welcome to my professional portfolio showcasing growth, artifact enhancements, and capstone self-assessment.
